<?php

declare(strict_types=1);

namespace Yiisoft\Middleware\Dispatcher\Event;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Server\MiddlewareInterface;

/**
 * `AfterMiddleware` event is raised after a middleware was executed.
 */
final class AfterMiddleware
{
    /**
     * @param MiddlewareInterface $middleware Middleware that was executed.
     * @param ResponseInterface|null $response Response generated by middleware or null in case there was an error.
     */
    public function __construct(
        private MiddlewareInterface $middleware,
        private ?ResponseInterface $response
    ) {
    }

    /**
     * @return MiddlewareInterface Middleware that was executed.
     */
    public function getMiddleware(): MiddlewareInterface
    {
        return $this->middleware;
    }

    /**
     * @return ResponseInterface|null Response generated by middleware or null in case there was an error.
     */
    public function getResponse(): ?ResponseInterface
    {
        return $this->response;
    }
}
