on:
  - pull_request
  - push

name: backwards compatibility
jobs:
  roave_bc_check:
    name: Roave BC Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Set ownership # Temporary fix for https://github.com/actions/runner/issues/2033
        run: chown -R $(id -u):$(id -g) $PWD
      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga
